export const BASE_URL_NODE = 'http://localhost:8001/';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUBMIT = 'LOGIN_SUBMIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SIGNUP_SUBMIT = 'SIGNUP_SUBMIT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const VERIFY_EMAIL_START = 'VERIFY_EMAIL_START';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL';

export const CONTACT_SUBMIT = 'CONTACT_SUBMIT';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAIL = 'CONTACT_FAIL';

export const PROFILE_INFO_SUBMIT = 'PROFILE_INFO_SUBMIT';
export const PROFILE_INFO_UPDATE = 'PROFILE_INFO_UPDATE';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';

export const FETCH_ACCOUNT_INFO = 'FETCH_ACCOUNT_INFO';
export const FETCH_ACCOUNT_FAIL = 'FETCH_ACCOUNT_FAIL';

export const CHANGE_PASSWORD_SUBMIT = 'CHANGE_PASSWORD_SUBMIT';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const FORGOT_PASSWORD_SUBMIT = 'FORGOT_PASSWORD_SUBMIT';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const VERIFY_RESET_LINK_FAIL = 'VERIFY_RESET_LINK_FAIL';
export const VERIFY_RESET_LINK_SUCCESS = 'VERIFY_RESET_LINK_SUCCESS';

export const RESET_SUBMIT = 'RESET_SUBMIT';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAIL = 'RESET_FAIL';

export const FETCH_COUNTRY_START = 'FETCH_COUNTRY_START'; 
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAIL = 'FETCH_COUNTRY_FAIL';

export const FETCH_POST_START = 'FETCH_POST_START';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';

export const POST_SAVE_START = 'POST_SAVE_START';
export const POST_SAVE_SUCCESS = 'POST_SAVE_SUCCESS';
export const POST_SAVE_FAIL = 'POST_SAVE_FAIL';

export const POST_EDIT_START = 'POST_EDIT_START';
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
export const POST_EDIT_FAIL = 'POST_EDIT_FAIL';

export const POST_DETAIL_START = 'POST_DETAIL_START'; 
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS'; 
export const POST_DETAIL_FAIL = 'POST_DETAIL_FAIL';

export const POST_DETAIL_SLUG_START = 'POST_DETAIL_SLUG_START';
export const POST_DETAIL_SLUG_SUCCESS = 'POST_DETAIL_SLUG_SUCCESS';
export const POST_DETAIL_SLUG_FAIL = 'POST_DETAIL_SLUG_FAIL';

export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL'; 

export const FETCH_WEATHER_START = 'FETCH_WEATHER_START'; 
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS'; 
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';

export const GET_POST_START = 'GET_POST_START'; 
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'; 
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const GET_CATEGORY_POST_START = 'GET_CATEGORY_POST_START';
export const GET_CATEGORY_POST_SUCCESS = 'GET_CATEGORY_POST_SUCCESS';
export const GET_CATEGORY_POST_FAIL = 'GET_CATEGORY_POST_FAIL'; 

export const FETCH_OTHER_DATA = 'FETCH_OTHER_DATA'; 
export const FETCH_OTHER_FAIL = 'FETCH_OTHER_FAIL'; 

export const SEARCH_POST_SUBMIT = 'SEARCH_POST_SUBMIT';
export const SEARCH_POST_SUCCESS = 'SEARCH_POST_SUCCESS';
export const SEARCH_POST_FAIL = 'SEARCH_POST_FAIL'; 
